// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owagekqtnfiwgvlmnhar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93YWdla3F0bmZpd2d2bG1uaGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDg0ODgsImV4cCI6MjA2ODE4NDQ4OH0.TSN3aW3Qyue_UAp5aHqX-dnl-92aeMHb2-4e_TTWcP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});